#!/usr/bin/env bash

COMMIT_MESSAGE=$(cat "$1")
COMMIT_TYPES="fix|feat|docs|test|perf|refactor|chore|cleanup|remove"
COMMIT_REGEX='^('${COMMIT_TYPES}')(\([a-zA-Z0-9_/]+\))?:\s.*$'
MERGE_REGEX='^Merge branch [^\r\n]+'

if ! [[ $COMMIT_MESSAGE =~ $COMMIT_REGEX || $COMMIT_MESSAGE =~ $MERGE_REGEX ]]; then
	echo -e "ERRO:\tA mensagem do commit não segue o padrão esperado:"
	echo -e "\ttipo_commit(local): breve descrição do commit\n"
	echo -e "tipo_commit pode ser alguma das seguintes chaves: ${COMMIT_TYPES}\n"
	exit 1
fi

exit 0
