#!/usr/bin/env bash

HAS_ERRORS=0

function testRepositoriesInternalError()
{
    LERROR_INTERNAL="lerror.GetInternal"

    CHANGED_REPOSITORIES=$(git diff HEAD --name-only \
        | grep '^adapters/sqlite/.*\.go$' \
        | grep -v '\(get_repositories\|_test\)\.go$'
    )

    for REP in $CHANGED_REPOSITORIES
    do
        readarray -t RETURNS_LIST < <(grep return "$REP")
        RETURNS_COUNT=${#RETURNS_LIST[@]}

        readarray -t SET_INTERNAL_ERROR_LIST < <(grep "$LERROR_INTERNAL" "$REP")
        SET_INTERNAL_ERROR_COUNT=${#SET_INTERNAL_ERROR_LIST[@]}

        if [ "$RETURNS_COUNT" -gt "$SET_INTERNAL_ERROR_COUNT" ]; then
            echo "Erro: $REP tem $RETURNS_COUNT chamada(s) à 'return', porém, tem $SET_INTERNAL_ERROR_COUNT chamada(s) à '$LERROR_INTERNAL'"
            HAS_ERRORS=1
        fi
    done
}

function testNotFound()
{
    LERROR_NOTFOUND="lerror.GetNotFound"

    CHANGED_USECASES=$(git diff HEAD --name-only \
        | grep '^core/usecase/.*\.go$' \
        | grep -v '_test\.go$'
    )

    for USECASE in $CHANGED_USECASES
    do
        readarray -t NOT_EXISTS_LIST < <(grep "!exists" "$USECASE")
        NOT_EXISTS_COUNT=${#NOT_EXISTS_LIST[@]}

        readarray -t GET_BADREQUEST_ERROR_LIST < <(grep "$LERROR_NOTFOUND" "$USECASE")
        GET_BADREQUEST_ERROR_COUNT=${#GET_BADREQUEST_ERROR_LIST[@]}

        if [ "$NOT_EXISTS_COUNT" -gt "$GET_BADREQUEST_ERROR_COUNT" ]; then
            echo "Erro: $USECASE tem $NOT_EXISTS_COUNT verificações de existência de itens do domínio, porém, tem $GET_BADREQUEST_ERROR_COUNT chamada(s) à '$LERROR_NOTFOUND'"
            HAS_ERRORS=1
        fi
    done
}

function testUuidError()
{
    LERROR_INTERNALF="lerror.GetInternals"

    CHANGED_FILES=$(git diff HEAD --name-only)

    for FILE in $CHANGED_FILES
    do
        readarray -t LUUID_NEW_LIST < <(grep "luuid.New()" "$FILE")
        LUUID_NEW_COUNT=${#LUUID_NEW_LIST[@]}

        readarray -t SET_INTERNALF_ERROR_LIST < <(grep "$LERROR_INTERNALF" "$FILE")
        SET_INTERNALF_ERROR_COUNT=${#SET_INTERNALF_ERROR_LIST[@]}

        if [ "$LUUID_NEW_COUNT" -gt "$SET_INTERNALF_ERROR_COUNT" ]; then
            echo "Erro: $FILE tem $LUUID_NEW_COUNT chamada(s) à 'luuid.New', porém, tem $SET_INTERNALF_ERROR_COUNT chamada(s) à '$LERROR_INTERNALF'"
            HAS_ERRORS=1
        fi
    done
}

testRepositoriesInternalError
testNotFound
testUuidError

exit $HAS_ERRORS
