#!/usr/bin/env bash

HAS_ERRORS=0

function testRepositoriesInternalError()
{
    LERROR_INTERNAL="lerror.Internal"

    CHANGED_REPOSITORIES=$(git diff HEAD --name-only \
        | grep '^adapters/sqlite/.*\.go$' \
        | grep -v '\(get_repositories\|_test\)\.go$'
    )

    for REP in $CHANGED_REPOSITORIES
    do
        readarray -t RETURNS_LIST < <(grep return "$REP")
        RETURNS_COUNT=${#RETURNS_LIST[@]}

        readarray -t SET_INTERNAL_ERROR_LIST < <(grep "$LERROR_INTERNAL" "$REP")
        SET_INTERNAL_ERROR_COUNT=${#SET_INTERNAL_ERROR_LIST[@]}

        if [ "$RETURNS_COUNT" -gt "$SET_INTERNAL_ERROR_COUNT" ]; then
            echo "Erro: $REP tem $RETURNS_COUNT chamada(s) à 'return', porém, tem somente $SET_INTERNAL_ERROR_COUNT chamada(s) à '$LERROR_INTERNAL'"
            HAS_ERRORS=1
        fi
    done
}

function testUuidError()
{
    LERROR_INTERNALF="lerror.Internalf"

    CHANGED_FILES=$(git diff HEAD --name-only)

    for FILE in $CHANGED_FILES
    do
        readarray -t LUUID_NEW_LIST < <(grep "luuid.New()" "$FILE")
        LUUID_NEW_COUNT=${#LUUID_NEW_LIST[@]}

        readarray -t SET_INTERNALF_ERROR_LIST < <(grep "$LERROR_INTERNALF" "$FILE")
        SET_INTERNALF_ERROR_COUNT=${#SET_INTERNALF_ERROR_LIST[@]}

        if [ "$LUUID_NEW_COUNT" -gt "$SET_INTERNALF_ERROR_COUNT" ]; then
            echo "Erro: $FILE tem $LUUID_NEW_COUNT chamada(s) à 'luuid.New', porém, tem somente $SET_INTERNALF_ERROR_COUNT chamada(s) à '$LERROR_INTERNALF'"
            HAS_ERRORS=1
        fi
    done
}

testRepositoriesInternalError
testUuidError

exit $HAS_ERRORS
